import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { BiMenu, BiX } from "react-icons/bi";

const Navbar = () => {
  const menu_burger = [1, 2, 3];

  const [dropmenu, setDropmenu] = useState(false);

  const showMenu = (event) => {
    setDropmenu((current) => !current);
  };

  return (
    <div className="flex flex-col flex-wrap justify-between sticky top-0">
      <Head>
        <title>Portfolio_Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.ico" />
      </Head>

      <nav className=" font-mono bg-[#161B22] text-white  box-border flex justify-between flex-row flex-wrap py-1 items-center">
        <Link href="/">
          <Image
            src="/logog.png"
            alt="Logo"
            width={180}
            height={50}
            className=""
          />
        </Link>

        <ul className=" max-md:hidden flex ">
          <li className="">
            <Link href={"projects"}>
              <button className=" hover:bg-slate-500 rounded-lg px-1 py-1  border-solid border-2 mx-1">
                Projects
              </button>
            </Link>
          </li>
          <li className=" ">
            <Link href={"portfolio"}>
              <button className=" hover:bg-slate-500 rounded-lg px-1 py-1  border-solid border-2 mx-1 ">
                Portfolio
              </button>
            </Link>
          </li>
          <li className=" ">
            <Link href={"contact"}>
              <button className=" hover:bg-slate-500 rounded-lg px-1 py-1  border-solid border-2 mx-1">
                Contact me
              </button>
            </Link>
          </li>
          <li className="">
            <Link href={"code_bits"}>
              <button className=" hover:bg-slate-500 rounded-lg px-2 py-1  border-solid border-2 mr-5 ">
                Code_Bits
              </button>
            </Link>
          </li>
        </ul>
        <div className=" md:hidden overflow-hidden mr-3" onClick={showMenu}>
          <button className="  md:hidden  text-xl flex flex-col  p-2">
            {dropmenu ? <BiX /> : <BiMenu />}
          </button>
          <div
            className={
              dropmenu
                ? "block   md:hidden text-white  box-border  bg-gray-900  p-1 rounded fixed top-16 right-0 text-lg"
                : "hidden    md:hidden text-white  box-border  bg-gray-900  p-1 rounded fixed top-16 right-0 text-lg"
            }
          >
            <Link
              href="projects"
              className="  hover:bg-slate-700 px-6 py-2 rounded  block"
            >
              Projects
            </Link>
            <Link
              href="portfolio"
              className=" hover:bg-slate-700 px-6 py-2 rounded block"
            >
              Portfolio
            </Link>
            <Link
              href="contact"
              className=" hover:bg-slate-700 px-6 py-2 rounded block"
            >
              Contact me
            </Link>
            <Link
              href="code_bits"
              className=" hover:bg-slate-700 px-6 py-2 rounded block"
            >
              Code_Bits
            </Link>
          </div>
        </div>
      </nav>
    </div>
  );
};

export default Navbar;
