import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { BiMenu, BiX } from "react-icons/bi";
import Button from "../components/button";
import { useSession } from "next-auth/react";
import { FiUserCheck } from "react-icons/fi";

const Navbar = () => {
  const { data: session, status } = useSession();

  const [dropmenu, setDropmenu] = useState(false);

  var isLoggedin;
  if (status === "authenticated") {
    isLoggedin = true;
  }
  const showMenu = (event) => {
    setDropmenu((current) => !current);
  };
  const signout = false;
  return (
    <div className="flex flex-col flex-wrap justify-between sticky top-0">
      <Head>
        <title>Portfolio_Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mini.ico" />
      </Head>

      <nav className=" font-mono bg-[#161B22] text-white  box-border flex justify-between flex-row flex-wrap py-1 items-center">
        <Link href="/">
          <Image
            src="/logog.png"
            alt="Logo"
            width={180}
            height={50}
            className=""
          />
        </Link>

        <ul className=" max-md:hidden flex  items-center pr-4">
          {session ? (
            <li className=" font-serif text-xl pr-4">
              <p>
                Hello,{" "}
                <span className=" text-green-500">{session?.userName}</span>
              </p>
            </li>
          ) : (
            ""
          )}

          <li className=" ">
            <Link href={"/portfolio"}>
              <Button
                button_text={"Portfolio"}
                className={
                  " border-navbar hover:border-green-500 hover:text-green-500 transition-colors"
                }
              />
            </Link>
          </li>
          <li className=" ">
            <Link href={"/contact"}>
              <Button
                button_text={"Contact_me"}
                className={
                  " border-navbar hover:border-green-500 hover:text-green-500 transition-colors"
                }
              />
            </Link>
          </li>
          <li className="">
            <Link href={"/code_bits"}>
              <Button
                button_text={"Code_Bits"}
                className={
                  " border-navbar hover:border-green-500 hover:text-green-500 transition-colors"
                }
              />
            </Link>
          </li>

          {isLoggedin ? (
            <>
              <li className=" text-white  border-2 rounded-md border-navbar hover:border-green-500 hover:text-green-500 transition duration-700">
                <Link href={"/dashboard/user"} className="p-2 text-lg block">
                  <FiUserCheck />
                </Link>
              </li>
              <li className="">
                <Link href={"/logout"}>
                  <Button
                    button_text={"Logout"}
                    className={
                      " border-navbar hover:border-red-500 hover:text-red-500"
                    }
                  />
                </Link>
              </li>
            </>
          ) : (
            <li className="">
              <Link href={"/login"}>
                <Button
                  button_text={"Login"}
                  className={
                    " border-navbar hover:border-green-500 hover:text-green-500 transition-colors"
                  }
                />
              </Link>
            </li>
          )}
        </ul>
        <div className=" md:hidden overflow-hidden mr-3" onClick={showMenu}>
          {session ? (
            <p className=" font-serif text-xl pr-4 float-left">
              Hello,{" "}
              <span className=" text-green-500">{session?.userName}</span>
            </p>
          ) : (
            ""
          )}
          <button className="  md:hidden  text-xl flex flex-col p-1 border-2 rounded hover:text-green-500 hover:border-green-500 transition-colors ">
            {dropmenu ? <BiX /> : <BiMenu />}
          </button>
          <div
            className={
              dropmenu
                ? "block   md:hidden text-white  box-border  bg-gray-700  p-1 rounded fixed top-16 right-0 text-lg mr-2"
                : "hidden"
            }
          >
            <Link
              href="/portfolio"
              className="  hover:text-green-500 border-2 border-gray-700 transition duration-300 hover:border-green-500 px-6 py-2 rounded block"
            >
              Portfolio
            </Link>
            <Link
              href="/contact"
              className="  hover:text-green-500 border-2 border-gray-700 transition-colors duration-300 hover:border-green-500 px-6 py-2 rounded block"
            >
              Contact_me
            </Link>
            <Link
              href="/code_bits"
              className="  hover:text-green-500 border-2 border-gray-700 transition-colors duration-300 hover:border-green-500 px-6 py-2 rounded block"
            >
              Code_Bits
            </Link>

            <Link
              href="/login"
              className="  hover:text-green-500 border-2 border-gray-700 transition-colors duration-300 hover:border-green-500 px-6 py-2 rounded block"
            >
              Login
            </Link>
            {!signout ? (
              <Link
                href="/logout"
                className="  hover:text-green-500 border-2 border-gray-700 transition-colors duration-300 hover:border-green-500 px-6 py-2 rounded block"
              >
                Logout
              </Link>
            ) : (
              ""
            )}
          </div>
        </div>
      </nav>
    </div>
  );
};

export default Navbar;
