import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const menu_burger = [1, 2, 3];

  const [dropmenu, setDropmenu] = useState(false);

  const showMenu = (event) => {
    setDropmenu((current) => !current);
  };

  const hidemenu = (e) => {
    if (!(e.target.tagName == "BUTTON")) {
      setDropmenu(false);
    }
  };

  return (
    <div
      className="  min-h-screen bg-[#010409] flex flex-col flex-wrap justify-between"
      onClick={hidemenu}
    >
      <Head>
        <title>Portfolio_Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <main className=" box-border">
        <nav className=" font-mono bg-[#161B22] text-white  box-border flex justify-between flex-row flex-wrap py-1 items-center">
          <Link href={""}>
            <Image
              src="/logog.png"
              alt="Logo"
              width={180}
              height={50}
              className=""
            />
          </Link>

          <ul className=" max-md:hidden flex ">
            <li className="">
              <Link href={""}>
                <button className=" hover:bg-slate-500 rounded-lg px-1 py-1  border-solid border-2 mx-1">
                  Projects
                </button>
              </Link>
            </li>
            <li className=" ">
              <Link href={""}>
                <button className=" hover:bg-slate-500 rounded-lg px-1 py-1  border-solid border-2 mx-1 ">
                  Portfolio
                </button>
              </Link>
            </li>
            <li className=" ">
              <Link href={""}>
                <button className=" hover:bg-slate-500 rounded-lg px-1 py-1  border-solid border-2 mx-1">
                  Contact me
                </button>
              </Link>
            </li>
            <li className="">
              <Link href={""}>
                <button className=" hover:bg-slate-500 rounded-lg px-2 py-1  border-solid border-2 mr-5 ">
                  Code_Bits
                </button>
              </Link>
            </li>
          </ul>
          <div
            className="group/menu md:hidden overflow-hidden mr-3"
            onClick={showMenu}
          >
            <button className="  md:hidden  text-xl flex flex-col  p-2 ">
              {menu_burger.map((time, key) => (
                <div
                  className="menu-burger bg-white w-4 m-[2px] border-white rounded-md "
                  style={{ height: "2px" }}
                  key={key}
                ></div>
              ))}
            </button>
            <div
              className={
                dropmenu
                  ? "block group-hover/menu:block  md:hidden text-white  box-border  bg-gray-900  p-1 rounded fixed top-16 right-0 text-lg"
                  : "hidden  group-hover/menu:block  md:hidden text-white  box-border  bg-gray-900  p-1 rounded fixed top-16 right-0 text-lg"
              }
            >
              <Link
                href=""
                className="  hover:bg-slate-700 px-6 py-2 rounded  block"
              >
                Projects
              </Link>
              <Link
                href=""
                className=" hover:bg-slate-700 px-6 py-2 rounded block"
              >
                Portfolio
              </Link>
              <Link
                href=""
                className=" hover:bg-slate-700 px-6 py-2 rounded block"
              >
                Contact me
              </Link>
              <Link
                href=""
                className=" hover:bg-slate-700 px-6 py-2 rounded block"
              >
                Code_Bits
              </Link>
            </div>
          </div>
        </nav>
      </main>
      <footer className=" font-mono bg-[#161B22] text-white  box-border flex flex-col items-end  flex-wrap py-1 ">
        <p className=" pr-5">
          Designed by{" "}
          <span>
            <a>@FahimaJahan</a>
          </span>
        </p>
        <p className=" pr-5">
          Developed by{" "}
          <span>
            <a>@FaisalAhamedRahad</a>
          </span>
        </p>
      </footer>
    </div>
  );
}
